### ISSUE TITLE
Add a docker file

### ISSUE THREAD

**Issue by rkpattnaik780** [rkpattnaik780/rk-votingappfcc#1]
Add a docker file so that the app can be run inside a docker container. To learn more, checkout this link - [dockerizing a nodejs webapp](https://nodejs.org/de/docs/guides/nodejs-docker-webapp/).

**Comment by kejriwalayushi28** [comment]
@rkpattnaik780  I would like to pick this.

**Comment by Tamy123** [comment]
Can i do this too?
