### ISSUE TITLE
Change instances of hosted url

### ISSUE THREAD

**Issue by rkpattnaik780** [rkpattnaik780/rk-votingappfcc#2]
Earlier the app was hosted in [rk-votingappfcc.herokuapp.com]() which has been now changed to [https://infinite-chamber-50445.herokuapp.com/](https://infinite-chamber-50445.herokuapp.com/). However, the README has still various links pointing towards the old obsolete link. Remove all instances of old url with the new url.

**Comment by NukeTheFridge** [comment]
@rkpattnaik780 I would like to take this issue.

**Comment by yatip** [comment]
@rkpattnaik780  can I work on this?

**Comment by rkpattnaik780** [comment]
@yatip , go ahead.
